= Detectie van energie-intensieve apparaten ten behoeve flexoplossingen (DEIA)

Dit ontwerp beschrijft het beoogde gebruiksscenario voor het dataproduct DEIA (_**D**etectie van **E**nergie-**I**ntensieve **A**pparaten ten behoeve flexoplossingen_), alsmede haar achterliggende architectuur en de gemaakte keuzes. 

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Zonnepanelen (PV), thuislaadpunten (EV), warmtepompen (WP, ook wel afgekort tot HP (_heat pumps_)) en thuisbatterijen (BESS, _Battery Energy Storage System_) zijn energie-intensieve apparaten. Zowel netbeheerders als andere partijen (_derden_) willen graag weten waar zij zich bevinden en hoe energie-intensief zij zijn. Data Scientist teams bij de drie grote netbeheerders werken samen om statistische modellen te maken die dit inzicht kunnen geven.

De epic bestaat uit drie fasen, een _pilot fase_, een _landelijke fase_ en een _data deel_ fase. Het dataproduct DEIA wordt alleen in de fase data delen gebruikt.

=== Pilot fase

In de pilot fase wordt een jaar lang de verbruiksdata van de slimme meters van 620 vrijwilligers gebruikt om het statistische model te ontwikkelen en te trainen. Dit model is géén dataproduct.

=== Landelijke fase

In de landelijke fase wordt het statistische model landelijk toegepast op alle aansluitingen waarvoor de _use case_ is link:https://www.netbeheernederland.nl/Goedgekeurde_use_cases[goedgekeurd]. Het betreft dan niet alleen maar slimme meter data. Deze fase resulteert in een tabel met voor elk energie-intensief apparaat (PV, EV, WP, BESS) het geschatte vermogen (in kiloWatt piek (kW(p))) met een bijbehorende betrouwbaarheid (_Confidence Level_ in procenten). Deze tabel wordt periodiek bijgewerkt. Zij is per aansluiting en kan geaggregeerd worden tot middenspanningsruimte (MS/LS-trafo) of tot postcode 6-niveau niveau en tot gebiedsniveau. Formeel zijn dit geen dataproducten omdat ze worden uitgewisseld tussen netbeheerders onderling.

.Voorbeeld eindresultaat (uniform overzicht geaggregeerd op MS/LS-trafo)
[cols= "1, 1, 1, 1"]
|===
|PowerTransformer |DeviceKind |ConfidenceLevel (%) |PeakPower (kW(p))
|123 |BESS |95 |123 
|123 |PV |97 |150
|127 |HP |65 |77
|123 |PV |99 |60
|===


=== Data deel fase

In de data deel fase wordt het statistische model uit de landelijke fase gebruikt om het uniforme overzicht te ontsluiten naar derden.

De data bestaat uit kwartierwarden van 10 dagen per kwartaal. PV- en BESS-data is invoedingsdata en mogen op aansluitniveau gedeeld worden. WP- en EV-data zijn afnamedata en mogen niet op aansluitniveau gedeeeld worden.

== Functionele eisen

Het dataproduct moet voldoen aan functionele eisen; deze vertellen wie ("*Als rol*") welke data ("*Wil ik*") nodig heeft en waarom ("*Want*"). Deze functionele eisen zijn alleen van toepassing op de fase data delen. Dat komt doordat dat de enige fase is met een dataproduct.

.Functionele eisen
[cols="1, 1, 8, 8"]
|===
|ID |Als rol |Wil ik |Want

 |{counter:fe} 
 |Regionale Netbeheerder (RNB)
 |Een uniform overzicht van aansluitingen en het gedrag van invoeding en afname in de tijd
 |Ik wil deze informatie laten verrijken zodat er een analyse op uitgevoerd kan worden die met grote zekerheid kan vaststellen of zich achter deze aansluiting een van de volgende vijf apparaattypes bevindt: zonnepanelen (PV), thuislaadpunten (EV), warmtepompen (WP),  thuisbatterijen (BESS) of apparaten tbv elektrisch koken

 |{counter:fe} 
 |Regionale Netbeheerder (RNB)
 |Een uniform overzicht van aansluitingen waarachter zich energie-intensieve apparaten bevinden
 |Ik wil de aangeslotene in staat stellen om de verbruiksdata van haar slimme meter, met haar toestemming, te delen met aanbiedingen van flexoplossingen


 |{counter:fe} 
 |Derde
 |Een uniform overzicht van de aanwezigheid en het geschatte piekvermogen, met een _Confidence Level_,  van energie-intensieve apparaten (PV, EV, WP en BESS) achter een transformator
a|
* Als gemeente wil ik weten waar er behoefte is aan publieke laadpalen. 
* Als brandweer wil ik weten waar thuisbatterijen een verhoogd risico zijn.
* Als flexaanbieder wil ik gebruikers van energie-intensieve apparaten een flexpropositie kunnen doen.

|===

== Dataservice

=== Gebruiksscenario - Centraal dataproduct

In de data delen fase is er gekozen voor een centraal scenario waarbij de aangeslotene toestemming verleent aan een flexaanbieder om een flexpropositie te doen.

.Gebruiksscenario: Centraal dataproduct
[d2,svg,theme=4]
----

include::partial$diagrams/detectie/gebruiksscenario-centraal.d2[]

----

1. Een derde of een RNB vraagt een uniform overzicht op bij de EDSN.
2. De Centrale Dataopslag verstrekt het gevraagde uniforme overzicht.

=== Gebruiksscenario - Decentraal dataproduct

In de data delen fase is er gekozen voor een centraal scenario waarbij de aangeslotene toestemming verleent aan een flexaanbieder om een flexpropositie te doen.

.Gebruiksscenario: Decentraal dataproduct
[d2,svg,theme=4]
----

include::partial$diagrams/detectie/gebruiksscenario-decentraal.d2[]

----

1. Een derde of een RNB vraagt een uniform overzicht bij alle relevante RNBs.
2. Elke relevante RNB verstrekt het gevraagde uniforme overzicht.
3. De aanvrager consolideert de ontvangen uniforme overzicht tot een geconsolideerd uniform overzicht.



=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4]
----

include::partial$diagrams/detectie/architecture.d2[]

include::partial$diagrams/legend.d2[]

include::partial$diagrams/classes.d2[]

----

De structuur van de dataset is gebaseerd op het _Begrippenmodel NBNL_ en het _Common Information Model_

== Dataset

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

==== Dataset

[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, < 100MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Hoog

|Velocity
|Laag
|===

== Voorwaarden

Dit dataproduct wordt als _gesloten dataproduct_ aangeboden, onder de grondslag _Grondslag Toestemming_. De grondslag is vereist omdat een derde de aanvraag doet.

== Beslissingen en aannames

[cols="1, 3, 6"]
|===
|ID |Type |Beschrijving

// 1 
|{counter:bea}
|Beslissing
|De Data Scientist teams verrijken de kwartierwaarden met locatiegegevens (PC6 danwel MS/LS-trafo)

// 2
 |{counter:bea} 
 |Aanname
 a|De Data Scientist teams verrijken de kwartierwaarden met 

* het correspondentieadres van de aangeslotene (ten behoeve van de flexaanbieder),
* het locatieadres van de aansluiting (ten behoeve van de aggregatie),
* de MS/LS-transformator van de aansluiting (ten behoeve van de aggregatie)

// 3
|{counter:bea}
|Aanname
|De uniforme overzichten worden periodiek bijgewerkt

// 4
|{counter:bea}
|Aanname
|In het centrale gebruikersscenario worden de uniforme overzichten ontsloten door EDSN.

// 5
|{counter:bea}
|Aanname
|In de data delen fase is alle landelijke data beschikbaar. Zowel de data van Alliander, Enexis en Stedin, als de data van Coteq, Rendo en Westland Infra.

// 6
|{counter:bea}
|Aanname
|In de data deel fase zal het statistische model hertraind moeten worden. Zowel periodiek als incidenteel, bijvoorbeeld met de komst van nieuwe relevante energie-intensieve apparaten.

// 7
|{counter:bea}
|Aanname
|In de data deel fase moet de parameter waarover geaggregeerd worden voor de aanvrager (derde en RNB) een herkenbare en bruikbare waarde zijn. Het is dus *geen* interne (RNB-specifieke) waarde.

// 8
|{counter:bea}
|Aanname
|In de data deel fase wordt de data op transformator (MS/LS) geaggregeerd. *Dus niet* op PC6 en ook niet op gebied.

// 9
|{counter:bea}
|Aanname
|In de data deel fase worden de dataproducten centraal (op één URLendpoint aangeboden). *Dus niet* fedratief via zes URLs (één per nebeheerder).

// 10
|{counter:bea}
|Aanname
|Het is mogelijk om een dataset, als onderdeel van de dataservice, gefilterd te verstrekken.

// 11
 |{counter:bea}
 |Aaname 
 |In de data deel fase wordt gekozen voor een open dataproduct. Dit houdt in dat er in dit ontwerp geen rekening wordt gehouden met alle faciliteiten die nodig zijn om een gesloten dataproduct te ontsluiten. *NB*: Er is een positief advies van GEMS vereist om deze beslissing definitief te nemen.

// 12
 |{counter:bea}
 |Aanname
 |Aan het einde van fase 2 is er één statistisch model dat alle zeven netbeheerders kunnen gebruiken op hun eigen data wanneer zij de juiste tooling hebben.

// 13
  |{counter:bea}
  |Aanname
  |De uitkomsten van het draaien van het statistische model dat aan het einde van fase 2 wordt opgeleverd is interoperabel; lees de datasets sluiten aan.

// 14
 |{counter:bea}
 |Aanname
 |Het statistische model wordt periodiek (driemaandelijks) gedraaid op de data van alle netbeheerders.

// 15
 |{counter:bea}
 |Aaname
 |CERES wordt de centrale opslagplek. En CERES kan gebruik maken van een autorisatie en authenticatie platform.

|===
