= Flexinzicht

Dit ontwerp beschrijft het beoogde gebruiksscenario voor het dataproduct Flexinzicht, alsmede haar achterliggende architectuur en de gemaakte keuzes. 

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Binnen Netbeheer Nederland (NBNL) lopen meerdere initiatieven die kunnen resulteren in dataproducten met  'flex-informatie'. Flexinzicht is een (verzameling van) open dataproduct(en), gebaseerd op de zogenoemde _bouwblokken_ (https://modellen.netbeheernederland.nl/data-products/information-models/nbnl-profile-group[NBNL Profile Group]), die deze initiatieven ondersteunt. 

== Functionele eisen

De initiatieven die door Flexinzicht worden ondersteund zijn:

1. _Benodigde flex per locatie_ (BBN-GV)
2. Epic _Capaciteitskaart Belastingprofielen_ (BBN-KV)
3. Epic _Netvooruitzicht_ (Meer inzicht)

Voor elk van deze initiatieven worden functionele eisen (_functional requirements_) vastgelegd die geharmoniseerd worden. Zij vertellen wie ("*Als rol*") welke data ("*Wil ik*") nodig heeft en welke meerwaarde er mee gecreëerd wordt ("*Want*"). 

.Functionele eisen
[cols="2, 2, 8, 8"]
|===
|ID |Als rol |Wil ik |Want

 |Algemeen {counter:fe} 
 |Derde
 |flex-informatie
a|Ik wil

* inzicht en
* financieel kunnen prikkelen.

|BBN-GV {counter:fe-bbngv}
|BBN-GV
|inzicht
|handelingsperspectief.

|BBN-KV {counter:fe-bbnkv}
|BBN-KV
|inzicht
|handelingsperspectief.

|MI {counter:fe-mi}
|Meer inzicht
|inzicht
|handelingsperspectief.

|===

== Dataservice

=== Gebruiksscenario

_Wordt later ingevuld._

== Dataset

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

==== Dataset

[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|_Wordt later ingevuld._

|Variety
|_Wordt later ingevuld._

|Veracity
|_Wordt later ingevuld._

|Velocity
|_Wordt later ingevuld._
|===

== Voorwaarden

Dit dataproduct wordt als _open_ dataproduct aangeboden.

== Beslissingen en aannames

[cols="2, 3, 6"]
|===
|ID |Type |Beschrijving

|BBN-GV {counter:bea-bbngv}
|Aanname
|BBN-GV

|BBN-KV {counter:bea-bbnkv}
|Aanname
|BBN-KV

|MI {counter:bea-mi}
|Aanname
|Meer inzicht

|===
