= NL CIM Profile Group

Dit ontwerp beschrijft het beoogde gebruiksscenario voor de ``NL CIM Profile
Group``, alsmede de achterliggende architectuur en gemaakte keuzes.

[NOTE]
====
include::partial$data_product.adoc[]
====

=== Leeswijzer

Dit document verwacht enige achtergrondkennis over het elektriciteitsnet en
affiniteit met het voortbrengingsproces (_Build_) van thema _Energy Data
Intelligence_. Niet alle hoofdstukken zullen voor alle lezers even relevant
zijn, dit document dient primair als centraal overzicht van de complete
oplossing voor de _NL CIM Profile Group_.

== Reikwijdte

De _NL CIM Profile Group_ is een verzameling CIM profielen (zie
<<_common_information_model>>) om informatie uit te wisselen over het Nederlandse
elektriciteitsnet. De beschreven profielen ondersteunen meerdere
gebruiksscenario's en vormen een herbruikbaar en interoperabel component van de
door de gezamelijke netbeheerders gepubliceerde dataproducten.

=== Common Information Model

Het Common Information Model (CIM) is een internationaal gestandaardiseerd
model voor gegevensuitwisseling in de energiesector, ontwikkeld door de
_International Electrotechnical Commission_ (IEC). Het CIM faciliteert de
interoperabiliteit tussen verschillende energiesystemen en -applicaties door
een uniforme en geformaliseerde taal te bieden.

Het CIM bestaat uit vier standaarden met verschillende doelen, die de betekenis
van componenten van het elektriciteitsnet beschrijven:

1. IEC 61968: ondersteuning van de bedrijfsvoering, zoals _asset_- en
werkordermanagement;
1. IEC 61970: bedrijfsvoering & netontwerp;
1. IEC 62325: marktfacilitering voor US- en EU-energiemarkten;
1. IEC 62746: decentrale opwekking van energie.

Deze vier standaarden beschrijven klassen van data, welke attributen er
vastgelegd worden per klasse en de relaties tussen klassen. Het zijn deze
klassen die de betekenis van "dingen" in de echte wereld uitdrukken voor een
specifiek doel.

Daarnaast wordt het _Netbeheer Nederland Begrippenmodel_ gehanteerd als basis
voor begrippen die al in gebruik zijn binnen de energiesector.

[NOTE]
====
Het toepassen van het CIM is het vertalen van de betekenis van componenten van
het elektriciteitsnet naar een passende, herbruikbare structuur voor het
invullen van een informatievraag.
====

Het CIM beschrijft naast de betekenis van data een proces om tot een specifieke
structuur te komen: profileren. Een profiel is een verzameling klassen die
samen één of meerdere use cases invullen, in een specifieke context.  Sommige
profielen zijn dermate breed toepasbaar dat deze ook zelf weer een standaard
worden, dan wel als enkel profiel of een verzameling van profielen: een
_Profile Group_. De _Common Grid Model Exchange Standard_ (CGMES) is een
voorbeeld van een gestandaardiseerde Profile Group, waarbij de TSO's binnen
Europa de onderliggende profielen gebruiken om operationele informatie over hun
netten met elkaar uit te wisselen.

== Rollen

De _NL CIM Profile Group_ kent meerdere stakeholders, elk met een eigen
verzameling behoeften en wensen. De <<_functionele_eisen>> behorend bij elke
rol worden in het volgende hoofdstuk beschreven.

.Rollen
[cols="1, 1"]
|===
|Rol |Beschrijving

|Netbeheerder
|

|Toezichthouder
|

|Dataverwerker
|
|===

== Functionele eisen

_Functionele eisen_ beschrijven wat een oplossing moet *doen*, en voor *wie*.
De meeste informatievragen over het elektriciteitsnet draaien rondom
bedrijfsvoering (nettoplogie, congestie en _power flow_), netontwerp
(nettopologie met een temporaal aspect) en marktfacilitering (meterstanden,
flexibiliteit). Onderstaand een detailoverzicht.

.Functionele eisen
[cols="1, 1, 1"]
|===
|Als Rol |Wil ik |Want

|...
|Capaciteit
|...

|...
|Belasting
|...

|...
|Netfunctie
|...

|...
|Werkzaamheden
|...

|...
|Wachtrij
|...

|...
|Geographical location
|...

|...
|Flexibiliteit
|...

|...
|Connectiviteit
|...

|...
|Knelpunt/congestie
|...

|...
|Aangeslotene
|...

|...
|Inzicht in het "waarom"
|...
|===

== Dataset

Elk profiel bestaat uit één of meerdere datasets onder één geüniformeerde
definitie beheerd door _Team Semantiek, NBNL_. Om de functionele eisen in te
vullen zijn de volgende profielen vereist:

.Profielen
[cols="1, 1, 1"]
|===
|Profiel |Beschrijving |Functionele eis(en)

|Asset (AS)
|*Fysieke* eigenschappen van componenten in het net
|

|Equipment (EQ)
|*Functionele* eigenschappen van componenten in het net (netfuncties)
|

|Geographical Location (GL)
|Locatie van componenten in het net
|

|Market (MKT)
|Marktfacilitering binnen EU-markten
|

|Operation (OP)
|Operationele meetwaarden, discreet en analoog
|

|State Variables (SV)
|Resultaat van loadflow- en kortsluitberekeningen
|

|Steady State Hypothesis (SSH)
|Stabiele toestand van het elektriciteitsnet
|

|Topology (TP)
|Nettopologie: generalisatie van _node/breaker_ naar _bus/branch_
|
|===

=== Afhankelijkheden

Profielen kennen afhankelijkheden, e.g. het opstellen van een  `Topology
Profile` vereist de beschikbaarheid van `Equipment`. Onderstaand een overzicht
van de afhankelijkheden. Deze afhankelijkheden zijn van toepassing bij het
beschikbaar maken van de datasets, een dataverwerker heeft alle datasets tot
haar beschikking.

.CIM Profile Group
[d2,svg,theme=4,scaledwidth=100%]
----
vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 5
grid-columns: 4

vertical-gap: 200
horizontal-gap: 200

1.class: empty
"Asset Management".class: enterprise
"Grid Measurement".class: grid
2.class: empty

Start.class: dataset
"Net Model Management".class: grid
"Topology Processing".class: grid
"State Estimation".class: grid

3.class: empty
GIS.class: enterprise
4.class: empty
"Market Facilitation".class: market

Start -> "Net Model Management"
"Net Model Management" -> "Topology Processing": "Equipment Profile\nSSH Profile"
"Net Model Management" -> GIS: "Equipment Profile"
"Net Model Management" -> "Grid Measurement": "Equipment Profile"
"Topology Processing" -> "State Estimation": "Topology Profile"
"Grid Measurement" -> "Topology Processing": "Operation Profile"
"Grid Measurement" -> "State Estimation": "Operation Profile"
GIS -> "Market Facilitation": "Geographical Location\nProfile"
"Asset Management" -> "Net Model Management": "Asset Profile"
"Topology Processing" -> "Market Facilitation": "Topology Profile"
"State Estimation" -> "Market Facilitation": "State Variables Profile"

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}

classes: {
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke: transparent
    }
  }
  grid: {
    style: {
      fill: "#eccfcb"
      shadow: true
    }
  }
  enterprise: {
    style: {
      fill: "#d1e7c2"
      shadow: true
    }
  }
  market: {
    style: {
      fill: "#fffbef"
      shadow: true
    }
  }
  dataset: {
    style: {
      shadow: true
    }
    width: 80
    height: 80
    shape: circle
  }
}
----

Bovenstaande afhankelijkheden hebben invloed op de <<_architectuur>> van de
dataservices en leggen <<_kwaliteitseisen>> op de beschikbaarheid van te
refereren datasets. Daarnaast is er een volgordelijkheid gebaseerd op het
onderscheid tussen _transmissie_ en _distributie_. Deze vraagstukken worden
verder uitgewerkt als onderdeel van de <<_dataservice>>.

=== Splitsing tussen functie en asset

[NOTE]
====
Uitleggen functie- & assetsplitsing, impact toelichten.
====

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

.Volume, variety, veracity, velocity
[cols="1, 1"]
|===
|Type |Beschrijving

|Volume
|Midden, < 1000MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Medium, sluit aan op het bestaande inzicht van de netbeheerder in het LS-net

|Velocity
|Laag, dataset verandert wanneer [todo]
|===

== Dataservice

=== Gebruiksscenario

Het volgende gebruiksscenario wordt ondersteund:

.Gebruiksscenario
[d2,svg,theme=4]
----
shape: sequence_diagram

vars: {
  d2-config: {
    pad: 20
  }
}

"TenneT": {
  "TenneT" -> "TenneT": "1. Publiceer dataset voor profiel"
}

"RNB": {
  "RNB" -> "TenneT": "2. Vraag dataset voor profiel op"
  "TenneT" -> "RNB": "3. Lever dataset"
  "RNB" -> "RNB": "4. Publiceer dataset voor profiel"
}

"Verwerker": {
  "Verwerker" -> "TenneT": "5. Vraag dataset voor profiel op"
  "TenneT" -> "Verwerker": "6. Lever dataset"

  "Verwerker" -> "RNB": "7. Vraag dataset voor profiel op"
  "RNB" -> "Verwerker": "8. Lever dataset"

  "Verwerker" -> "Verwerker": "9. Verwerk datasets"
}
----

1. ...
2. ...
3. ...
4. ...
5. ...
6. ...
7. ...
8. ...
9. ...

=== Kwaliteitseisen

Kwaliteitseisen (_non functionals_) beschrijven wat een oplossing moet *zijn*.
Voor dit ontwerp wordt de categorisering vanuit _ISO/IEC 25010_ aangehouden,
waar van toepassing.

.Kwaliteitseisen
[cols="1, 1, 1"]
|===
|Categorie |Beschrijving |Kwaliteitseisen

 |Prestaties
 |Snel en efficiënt functioneren, met minimale laadtijden en schaalbaar
a|

 |Overdraagbaarheid
 |Eenvoudig te verplaatsen of te migreren naar een andere omgeving
a|

 |Gebruiksvriendelijkheid
 |Intuïtief en makkelijk te gebruiken voor de eindgebruiker
a|

 |Betrouwbaarheid
 |Stabiel en foutbestendig, met een hoge beschikbaarheid
a|* integriteit -> Masterdata Management (MDM)

 |Beveiliging
 |Bescherming bieden tegen ongeautoriseerde toegang en datalekken
a|

 |Onderhoudbaarheid
 |Eenvoudig aanpasbaar en uitbreidbaar zijn
a|
|===

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4,scaledwidth=100%]
----
vars: {
  d2-config: {
    pad: 20
  }
}

Extract.class: ["verb"; "business"]

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  business_color: "" {
    style: {
      fill: "#ffffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  business_text: "Business" {
    shape: text
  }
  application_color: "" {
    style: {
      fill: "#afffff"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  application_text: "Application" {
    shape: text
  }
  technology_color: "" {
    style: {
      fill: "#afffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  technology_text: "Technology" {
    shape: text
  }
}

classes: {
  *: {
    style: {
      shadow: true
    }
  }
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
  verb: {
    style: {border-radius: 30}
  }
  noun: {
    style: {border-radius: 4}
  }
  artifact: {shape: page}
  business: {
    style: {
      fill: "#ffffaf"
    }
  }
  application: {
    style: {
      fill: "#afffff"
    }
  }
  technology: {
    style: {
      fill: "#afffaf"
    }
  }
}
----

* de structuur (logisch model) van de dataset behorende bij de profielen is
  gebaseerd op het _Begrippenmodel NBNL_ en het _Common Information Model_;
* aanlevering van de dataset vanuit de netbeheerder geschiedt via JSON-bestand.
* netbeheerders leveren de dataset aan via een eigen bestandslocatie;
* de profielen zijn vindbaar via het NBNL Dataportaal.

== Voorwaarden

Alle profielen behorend bij de _NL CIM Profile Group_ worden als _open data_
aangeboden.

== Beslissingen en aannames

.Beslissingen en aannames
[cols="1, 1"]
|===
|Type |Beschrijving

|Beslissing
|Profielen worden als decentraal dataproducten onder een gecentraliseerd schema beschikbaar gemaakt.
|===
