vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 5
grid-columns: 4

vertical-gap: 80
horizontal-gap: 160

"Netbeheerder".class: [noun; business]
1_2.class: empty
"Data Scientist".class: [noun; business]
1_4.class: empty

3_1.class: empty
Extract.class: [verb; business]
Transform.class: [verb; business]
Load.class: [verb; business]

"Slimme Meter Lezer".class: [noun; application]
"Slimme Meter".class: [noun; application]
3_3.class: empty
3_4.class: empty

4_1.class: empty
"C-ARM".class: [artifact; technology]
4_3.class: empty
4_4.class: empty

Extract -> Transform: "triggers"
Transform -> Load: "triggers"
"Slimme Meter" -> "Extract": "serves"
"Data Scientist" -> Extract: "assigned to"
"Data Scientist" -> Load: "assigned to"
"C-ARM" -> "Slimme Meter": "realises"
"Slimme Meter Lezer" -> "Slimme Meter": "accesses (read)"
"Netbeheerder" -> "Slimme Meter Lezer": "assigned to"