vars: {
  d2-config: {
    pad: 20
  }
}

shape: sequence_diagram

"DRNB": "Derde/RNB"
"DO": "RNBs"

"DRNB" -> "DO": "1. Verzoek om uniform overzichten"
"DO" -> "DRNB": "2. Verstrek de uniforme overzichten"
"DRNB" -> "DRNB": "3. Consolideer uniforme overzichten"