vars: {
  d2-config: {
    pad: 20
  }
}

shape: sequence_diagram

"DRNB": "Derde/RNB"
"CDO": "EDSN"

"DRNB" -> "CDO": "1. Verzoek om uniform overzicht"
"CDO" -> "DRNB": "2. Verstrek het uniforme overzicht"