vars: {
  d2-config: {
    pad: 20
  }
}

shape: sequence_diagram

Netbeheerder -> EDSN: 1. Lever gedetecteerde apparaten
EDSN -> EDSN: 2. Extract, transform & load
EDSN -> Netbeheerder: 3. Bevestig levering
Klant -> EDSN: 4. Vraag om gedetecteerde apparaten
EDSN -> Klant: 5. Lever gedetecteerde apparaten
