= Capaciteitskaart

Dit ontwerp beschrijft de beoogde gebruiksscenarios voor het dataproduct
https://netbeheer-nederland.github.io/docs/dp-capaciteitskaart/latest/[``Capaciteitskaart``],
alsmede de achterliggende architectuur en gemaakte keuzes.

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

De https://capaciteitskaart.netbeheernederland.nl/[Capaciteitskaart] van
Netbeheer Nederland consolideert en publiceert capaciteitsinformatie van de
gezamelijke netbeheerders (TSO & DSO) van Nederland. Hiervoor levert elke
netbeheerder een overzicht van voedingsgebieden en corresponderende
capaciteits- en projectinformatie.

== Functionele eisen

Dit dataproduct is onderheving aan functionele eisen: de informatievraag die
het dataproduct en onderliggende oplossing moet beantwoorden.

.Functionele eisen
[cols="1, 1, 3, 3"]
|===
|ID |Als Rol |Wil ik |Want

|{counter:fr}
|RNB
|inzicht in de schaarstekleur van een MS/LS trafo
|

|{counter:fr}
|RNB
|inzicht in welke postcodes worden bediend door een specifieke MS/LS trafo
|

|{counter:fr}
|RNB
|inzicht in welke buurten er door één of meerdere MS/LS trafo(s) worden bediend
|

|{counter:fr}
|RNB
|inzicht in welke MS-route de MS/LS trafo wordt bediend
|

|{counter:fr}
|RNB
|inzicht of er hoger in het net schaarste van toepassing is
|

|{counter:fr}
|RNB
|inzicht in welke projecten er zijn gepland voor een MS/LS trafo (en een buurt)
 om capaciteitsknelpunten op te lossen
|

|{counter:fr}
|RNB
|inzicht in de geplande bedrijfsname van een project
|

|{counter:fr}
|RNB
|inzicht in de eigenaar (netbeheerder) van de MS/LS trafo
|

|===

== Dataservice

=== Gebruiksscenario

Het volgende gebruiksscenario wordt ondersteund:

.Gebruiksscenario
[d2,svg,theme=4]
----
shape: sequence_diagram

vars: {
  d2-config: {
    pad: 20
  }
}

TenneT -> EDSN: 1. Lever dataset\: congestiegebieden
EDSN -> RNB: 2. Lever dataset\: onderstations
RNB -> EDSN: 3. Lever dataset\: voedingsgebieden
EDSN -> EDSN: 4. Publiceer kaart & dataproduct
EDSN -> RNB: 5. Bevestig publicatie
EDSN -> TenneT: 5. Bevestig publicatie
Gebruiker -> EDSN: 6. Vraag kaart op
EDSN -> Gebruiker: 7. Toon kaart
----

1. TenneT levert een dataset met congestiegebieden gebaseerd op onderstation
(OS). Deze dataset bevat ``EnergyArea``s, maar geen ``PostcodeArea``s
2. EDSN levert deze dataset door aan elke Regionale Netbeheerder (RNB) als
basis voor de invulling van de voedingsgebieden
3. Elke individuele RNB levert de dataset met de voedingsgebieden voor haar
dekkingsgebied aan bij _Energie Data Services Nederland_ (EDSN). Hierbij worden
worden voedingsgebieden -waar mogelijk- gekoppeld aan de voedingsgebieden van
TenneT
4. EDSN consolideert de aangeleverde datasets en visualiseert deze op een
interactieve, geografische kaart. De geconsolideerde (uit alle aanleveringen
samengevoegde) dataset wordt integraal aangeboden als downloadbaar bestand
(dataproduct)
5. EDSN bevestigt de ontvangst van de dataset en de publicatie van de kaart
6. Een gebruiker vraagt de kaart op, via een browser
7. De kaart wordt getoond aan de gebruiker

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4,scaledwidth=100%]
----
vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 5
grid-columns: 4

vertical-gap: 80
horizontal-gap: 160

1.class: empty
EDSN.class: [noun; business]
2.class: empty
3.class: empty

Netbeheerder.class: [noun; business]
Broker.class: [noun; business]
Consumer.class: [noun; business]
4.class: empty

5.class: empty
Extract.class: [verb; business]
Transform.class: [verb; business]
Load.class: [verb; business]

"EDSN File Gateway".class: [noun; application]
"Data Product".class: [noun; application]
"NBNL Dataportaal".class: [noun; application]
6.class: empty

7.class: empty
"JSON File".class: [artifact; technology]

Extract -> Transform: "triggers"
Transform -> Load: "triggers"
"Data Product" -> "Extract": "serves"
"NBNL Dataportaal" -> "Data Product": "accesses (read)"
Extract -> Consumer: "serves"
EDSN -> Broker: "assigned to"
Broker -> Extract: "assigned to"
"JSON File" -> "Data Product": "realises"
"EDSN File Gateway" -> "Data Product": "accesses (read)"
"EDSN File Gateway" -> "Netbeheerder": "serves"

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  business_color: "" {
    style: {
      fill: "#ffffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  business_text: "Business" {
    shape: text
  }
  application_color: "" {
    style: {
      fill: "#afffff"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  application_text: "Application" {
    shape: text
  }
  technology_color: "" {
    style: {
      fill: "#afffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  technology_text: "Technology" {
    shape: text
  }
}

classes: {
  *: {
    style: {
      shadow: true
    }
  }
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
  verb: {
    style: {border-radius: 30}
  }
  noun: {
    style: {border-radius: 4}
  }
  artifact: {shape: page}
  business: {
    style: {
      fill: "#ffffaf"
    }
  }
  application: {
    style: {
      fill: "#afffff"
    }
  }
  technology: {
    style: {
      fill: "#afffaf"
    }
  }
}

----

* de structuur van de dataset is gebaseerd op het
_Begrippenmodel NBNL_ en het _Common Information Model_;
* aanlevering van de dataset vanuit de netbeheerder geschiedt via JSON-bestand.
* netbeheerders leveren de dataset aan via de _File Gateway_ van EDSN; het
* dataproduct *Capaciteitskaart* is vindbaar via het NBNL Dataportaal.

== Dataset

De dataset beschrijft capaciteits- en wachtrij-informatie voor de
_voedingsgebieden_, bijbehorende _postcodes_ en _werkzaamheden_ die invloed
hebben op de beschikbare capaciteit.

=== Prognose

Bij een meerjarige prognose wordt een aparte dataset (als JSON-bestand) per
jaar opgeleverd door de netbeheerder. Hiermee kan de verschuiving in
beschikbare capaciteit worden geduid, naast verschuivingen in voedingsgebieden.
De bijbehorende metadata van de dataset specificeert voor welk jaar de dataset
van toepassing is.

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

[cols="1, 1"]
|===
|Type |Beschrijving

|Volume
|Laag, < 100MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Hoog, sluit aan op bestaande congestie/capaciteitsinformatie

|Velocity
|Driemaandelijkse update voor capaciteitsinformatie en werkzaamheden, maandelijks voor wachtrij-informatie
|===

== Voorwaarden

Dit dataproduct wordt als _open data_ aangeboden.

== Beslissingen en aannames

[cols="1, 1"]
|===
|Type |Beschrijving

|Beslissing
|Een voedingsgebied bestaat uit een of meerdere postcodegebieden.

|Beslissing
|Voor elk jaar (tot 2030) wordt een aparte dataset per jaar opgeleverd.

|Aanname
|Het dataproduct wordt opgevoerd in het NBNL Dataportaal.

|Aanname
|Voedingsgebieden zijn *niet* stabiel over de tijdsperiode voor prognoses.

|Aanname
|Op een later moment wordt mogelijk een ander integratiepatroon gehanteerd, zoals _Apache Iceberg_.
|===
